export const translations = {
  en: {
    appTitle: "TAXI TAWAT",
    driverMode: "Driver Login",
    passengerMode: "Passenger View",
    destinations: "Destinations from Ghardaia",
    availableTrips: "Available Trips",
    seatsAvailable: "seats available",
    noTrips: "No trips found for this destination.",
    callDriver: "Call Driver",
    back: "Back",
    updateSeats: "Update Available Seats",
    driverDashboard: "Driver Dashboard",
    myTrips: "My Trips",
    save: "Save",
    logout: "Logout",
    phone: "Phone Number",
    date: "Date",
    registerNow: "Register Now",
    fromGhardaia: "From Ghardaia",
    toGhardaia: "To Ghardaia",
    searchDriver: "Search driver name or phone...",
    enterFullName: "Full Name",
    enterPhonePassenger: "Your Phone Number",
    startNavigating: "Start Browsing",
    whatsappRequest: "WhatsApp Request",
    passengerLoginHeading: "Welcome to Taxi Tawat",
    waMsg: "Hello! I am",
    bookingConflict: "You already have a booking for this day!",
    myProfile: "My Profile",
    updateProfile: "Update Profile",
    addPhoto: "Add Photo",
    changePhoto: "Change Photo",
    enterEmail: "Email Address (Optional)",
    chooseRole: "Are you a Driver or a Traveler?",
    iAmDriver: "I am a Driver",
    iAmTraveler: "I am a Traveler",
    driverRegistrationHeading: "Driver Registration",
    licensePlate: "License Plate Number",
    carColor: "Car Color",
    enterLicensePlate: "Enter License Plate (e.g. 12345-120-47)",
    enterCarColor: "Enter Car Color (e.g. White, Silver)",
    route: "Route",
    chooseYourRoute: "Choose your active route",
    errorName: "Name cannot be empty or contain numbers",
    errorPhone: "Phone must be 10 digits starting with 05, 06, or 07",
    errorLicense: "License plate must match the format xx-xxx-xxxxx (numbers only)",
    statusAvailable: "Available",
    statusFull: "Full",
    statusOff: "Not Working",
    weeklySchedule: "Weekly Schedule",
    selectDate: "Select Date",
    manageAvailability: "Manage your 7-day availability",
    daySun: "Sun", dayMon: "Mon", dayTue: "Tue", dayWed: "Wed", dayThu: "Thu", dayFri: "Fri", daySat: "Sat",
    timeSlot: "Departure Time", seats: "Seats",
    bookNow: "Book Now",
    requestPending: "Pending Confirmation",
    requestConfirmed: "Booking Confirmed!",
    incomingRequests: "Active Booking Requests",
    confirm: "Confirm",
    cancel: "Cancel",
    passengerInfo: "Passenger Info",
    sendRequest: "Send Request",
    messageWhatsApp: "Message via WhatsApp",
    todayTrips: "Today's Trips",
    historyAll: "Passenger List",
    searchFilterPlaceholder: "...Filter by date, passenger, or city",
    specialDatesBlocked: "Special Dates Blocked",
    noBookingsToday: "No passenger bookings for today.",
    noTripsOnDate: "No trips found on this date.",
    noPastTrips: "No past trips or bookings.",
    overridesWeekly: "Overrides Weekly",
    pastDate: "Past Date",
    newNotification: "New Notification",
    accept: "Accept",
    decline: "Decline",
    notifications: "Notifications",
    carDetails: "Car Details",
    totalTrips: "Total Trips",
    activeStatus: "Active Status",
    rating: "Rating",
    driverProfile: "Driver Profile",
    to: "To",
    headingTo: "Heading to",
    confirmToCall: "Confirm booking to view number",
    passengerManifest: "Passenger Manifest"
  },
  fr: {
    appTitle: "TAXI TAWAT",
    driverMode: "Espace Chauffeur",
    passengerMode: "Espace Passager",
    destinations: "Destinations depuis Ghardaïa",
    availableTrips: "Trajets Disponibles",
    seatsAvailable: "places disponibles",
    noTrips: "Aucun trajet trouvé pour cette destination.",
    callDriver: "Appeler le Chauffeur",
    back: "Retour",
    updateSeats: "Mettre à jour les places",
    driverDashboard: "Tableau de Bord Chauffeur",
    myTrips: "Mes Trajets",
    save: "Enregistrer",
    logout: "Déconnexion",
    phone: "Numéro de téléphone",
    date: "Date",
    registerNow: "S'inscrire maintenant",
    fromGhardaia: "Depuis Ghardaïا",
    toGhardaia: "Vers Ghardaïa",
    searchDriver: "Rechercher un chauffeur ou num...",
    enterFullName: "Nom Complet",
    enterPhonePassenger: "Votre Numéro de Téléphone",
    startNavigating: "Commencer",
    whatsappRequest: "Réserver via WhatsApp",
    passengerLoginHeading: "Bienvenue sur Taxi Tawat",
    waMsg: "Bonjour ! Je suis",
    myProfile: "Mon Profil",
    updateProfile: "Mettre à jour le profil",
    addPhoto: "Ajouter une photo",
    changePhoto: "Changer la photo",
    enterEmail: "Adresse E-mail (Facultatif)",
    chooseRole: "Êtes-vous Chauffeur ou Passager ?",
    iAmDriver: "Je suis Chauffeur",
    iAmTraveler: "Je suis Passager",
    driverRegistrationHeading: "Inscription Chauffeur",
    licensePlate: "Numéro de Plaque d'immatriculation",
    carColor: "Couleur de la voiture",
    enterLicensePlate: "Entrez le numéro de plaque",
    enterCarColor: "Entrez la couleur de la voiture",
    route: "Itinéraire",
    chooseYourRoute: "Choisissez votre itinéraire",
    errorName: "Le nom ne peut pas être vide ou contenir des chiffres",
    errorPhone: "Le téléphone doit avoir 10 chiffres commençant par 05, 06 ou 07",
    errorLicense: "La plaque doit correspondre au format xx-xxx-xxxxx",
    statusAvailable: "Disponible",
    statusFull: "Complet",
    statusOff: "Pas de service",
    weeklySchedule: "Planning Hebdomadaire",
    selectDate: "Choisir une Date",
    manageAvailability: "Gérez votre disponibilité sur 7 jours",
    daySun: "Dim", dayMon: "Lun", dayTue: "Mar", dayWed: "Mer", dayThu: "Jeu", dayFri: "Ven", daySat: "Sam",
    timeSlot: "Heure de départ", seats: "Places",
    bookNow: "Réserver",
    requestPending: "En attente de confirmation",
    requestConfirmed: "Réservation Confirmée !",
    incomingRequests: "Demandes de Réservation",
    confirm: "Confirmer",
    cancel: "Annuler",
    passengerInfo: "Informations Passager",
    sendRequest: "Envoyer la demande",
    messageWhatsApp: "Contacter via WhatsApp",
    todayTrips: "Trajets d'aujourd'hui",
    historyAll: "Liste des Passagers",
    searchFilterPlaceholder: "...Filtrer par date, passager ou ville",
    specialDatesBlocked: "Dates spéciales bloquées",
    noBookingsToday: "Aucune réservation pour aujourd'hui.",
    noTripsOnDate: "Aucun trajet trouvé à cette date.",
    noPastTrips: "Aucun trajet ou réservation passé.",
    overridesWeekly: "Remplace l'hebdomadaire",
    pastDate: "Date passée",
    newNotification: "Nouvelle Notification",
    accept: "Accepter",
    decline: "Refuser",
    notifications: "Notifications",
    carDetails: "Informations Voiture",
    totalTrips: "Total Trajets",
    activeStatus: "Statut Actif",
    rating: "Évaluation",
    driverProfile: "Profil Chauffeur",
    to: "Vers",
    headingTo: "En direction de",
    bookingConflict: "Vous avez déjà une réservation pour ce jour !",
    confirmToCall: "Confirmez la réservation pour voir le numéro",
    passengerManifest: "Liste des Passagers"
  },
  ar: {
    appTitle: "تاكسي توات",
    driverMode: "دخول السائق",
    passengerMode: "واجهة المسافر",
    destinations: "الوجهات من غرداية",
    availableTrips: "الرحلات المتاحة",
    seatsAvailable: "مقاعد متاحة",
    noTrips: ".لا توجد رحلات لهذه الوجهة حاليا",
    callDriver: "اتصل بالسائق",
    back: "رجوع",
    updateSeats: "تحديث المقاعد المتاحة",
    driverDashboard: "لوحة تحكم السائق",
    myTrips: "رحلاتي",
    save: "حفظ",
    logout: "تسجيل خروج",
    phone: "رقم الهاتف",
    date: "التاريخ",
    registerNow: "سجل الآن",
    fromGhardaia: "من غرداية",
    toGhardaia: "إلى غرداية",
    searchDriver: "ابحث عن اسم السائق أو الرقم...",
    enterFullName: "الاسم الكامل",
    enterPhonePassenger: "رقم هاتفك",
    startNavigating: "تصفح الرحلات",
    whatsappRequest: "حجز عبر واتساب",
    passengerLoginHeading: "مرحباً بك في تاكسي توات",
    waMsg: "مرحباً! أنا",
    myProfile: "ملفي الشخصي",
    updateProfile: "تحديث الملف",
    addPhoto: "إضافة صورة",
    changePhoto: "تغيير الصورة",
    enterEmail: "البريد الإلكتروني (اختياري)",
    chooseRole: "هل أنت سائق أم مسافر؟",
    bookingConflict: "لديك حجز مسبق في هذا اليوم بالفعل!",
    iAmDriver: "أنا سائق",
    iAmTraveler: "أنا مسافر",
    driverRegistrationHeading: "تسجيل السائق",
    licensePlate: "رقم اللوحة",
    carColor: "لون السيارة",
    enterLicensePlate: "أدخل رقم لوحة السيارة",
    enterCarColor: "أدخل لون السيارة (مثال: أبيض، فضي)",
    route: "المسار",
    chooseYourRoute: "اختر مسارك",
    errorName: "يجب ألا يكون الاسم فارغاً ولا يحتوي على أرقام",
    errorPhone: "يجب أن يتكون رقم الهاتف من 10 أرقام تبدأ بـ 05 أو 06 أو 07",
    errorLicense: "يجب أن يتطابق رقم اللوحة مع النمط xx-xxx-xxxxx",
    statusAvailable: "متاح",
    statusFull: "مكتمل",
    statusOff: "لا يعمل",
    weeklySchedule: "الجدول الأسبوعي",
    selectDate: "اختر التاريخ",
    manageAvailability: "إدارة توفرك لمدة 7 أيام",
    daySun: "أحد", dayMon: "اثنين", dayTue: "ثلاثاء", dayWed: "أربعاء", dayThu: "خميس", dayFri: "جمعة", daySat: "سبت",
    timeSlot: "وقت الانطلاق", seats: "مقاعد",
    bookNow: "احجز الآن",
    requestPending: "في انتظار التأكيد",
    requestConfirmed: "تم تأكيد الحجز!",
    incomingRequests: "طلبات الحجز النشطة",
    confirm: "تأكيد",
    cancel: "إلغاء",
    passengerInfo: "بيانات المسافر",
    sendRequest: "إرسال الطلب",
    messageWhatsApp: "تواصل عبر واتساب",
    todayTrips: "رحلات اليوم",
    historyAll: "قائمة الركاب",
    searchFilterPlaceholder: "البحث عن طريق التاريخ، المسافر، أو المدينة...",
    specialDatesBlocked: "تواريخ خاصة محجوزة",
    noBookingsToday: ".لا توجد حجوزات مسافرين لهذا اليوم",
    noTripsOnDate: "لا توجد رحلات في هذا التاريخ",
    noPastTrips: ".لا توجد رحلات أو حجوزات سابقة",
    overridesWeekly: "يستبدل الأسبوعي",
    pastDate: "تاريخ سابق",
    newNotification: "إشعار جديد",
    accept: "قبول",
    decline: "رفض",
    notifications: "الإشعارات",
    carDetails: "معلومات السيارة",
    totalTrips: "إجمالي الرحلات",
    activeStatus: "الحالة النشطة",
    rating: "التقييم",
    driverProfile: "الملف الشخصي للسائق",
    to: "إلى",
    toGhardaia: "إلى غرداية",
    headingTo: "متوجه إلى",
    confirmToCall: "يجب تأكيد الحجز لرؤية الرقم",
    passengerManifest: "قائمة الركاب"
  }
};

export let destinationsList = [
  { id: '16', name: { en: 'Algiers', fr: 'Alger', ar: 'الجزائر العاصمة' }, icon: 'map-pin' },
  { id: '19', name: { en: 'Setif', fr: 'Sétif', ar: 'سطيف' }, icon: 'map-pin' },
  { id: '23', name: { en: 'Annaba', fr: 'Annaba', ar: 'عنابة' }, icon: 'map-pin' },
  { id: '25', name: { en: 'Constantine', fr: 'Constantine', ar: 'قسنطينة' }, icon: 'map-pin' },
  { id: '31', name: { en: 'Oran', fr: 'Oran', ar: 'وهران' }, icon: 'map-pin' }
];

export let trips = [
  { id: 1, driverId: 'd1', driverLicense: 'mock-d1', destinationId: '16', driverName: 'Omar B.',   phone: '0555123456', time: '08:00' },
  { id: 2, driverId: 'd2', driverLicense: 'mock-d2', destinationId: '16', driverName: 'Hassan T.', phone: '0555987654', time: '10:30' },
  { id: 3, driverId: 'd3', driverLicense: 'mock-d3', destinationId: '31', driverName: 'Kamel S.',  phone: '0770112233', time: '06:00' },
  { id: 4, driverId: 'd4', driverLicense: 'mock-d4', destinationId: '25', driverName: 'Yacine M.', phone: '0661445566', time: '07:30' },
  { id: 5, driverId: 'd5', driverLicense: 'mock-d5', destinationId: '31', driverName: 'Bilal R.',  phone: '0770998877', time: '14:00' }
];

// NOTE: All app state (currentLang, userRole, etc.) is managed by app.js.
// data.js only defines: translations, destinationsList, trips.
